<Project>
  <PropertyGroup>
    <Version>0.29.2</Version>
    <TargetGameVersion>RELEASE 4.4.0e</TargetGameVersion>
    <NetworkProtocolVersion>0</NetworkProtocolVersion>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="MemoryPackGenerator_TypeScriptOutputDirectory" />
  </ItemGroup>
</Project>
