<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MetaMystia.Network/MetaMystia.Network.csproj" />
    <ProjectReference Include="../MetaMystia.Schema/MetaMystia.Schema.csproj" />
  </ItemGroup>
</Project>
