using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace MetaMystia.Generators
{
    [Generator]
    public sealed class BehaviorRegistryGenerator : IIncrementalGenerator
    {
        private const string AttributeMetadataName = "MetaMystia.Network.NetActionBehaviorAttribute";

        private static readonly DiagnosticDescriptor MissingRegisterRule = new(
            id: "MMNET001",
            title: "Net action behavior is missing Register",
            messageFormat: "Net action behavior '{0}' must declare 'public static void Register(NetActionDispatcher dispatcher)'",
            category: "MetaMystia.Network",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var behaviorProvider = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeMetadataName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => GetBehaviorInfo(ctx))
                .Where(static info => info.HasValue)
                .Select(static (info, _) => info!.Value);

            context.RegisterSourceOutput(behaviorProvider.Collect(), GenerateRegistry);
        }

        private static BehaviorInfo? GetBehaviorInfo(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol symbol)
                return null;

            return new BehaviorInfo(
                symbol.Name,
                symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                HasMatchingRegister(symbol),
                symbol.Locations.FirstOrDefault(location => location.IsInSource));
        }

        private static bool HasMatchingRegister(INamedTypeSymbol symbol)
        {
            return symbol.GetMembers("Register")
                .OfType<IMethodSymbol>()
                .Any(static method =>
                    method.MethodKind == MethodKind.Ordinary &&
                    method.DeclaredAccessibility == Accessibility.Public &&
                    method.IsStatic &&
                    method.ReturnsVoid &&
                    method.Parameters.Length == 1 &&
                    method.Parameters[0].RefKind == RefKind.None &&
                    IsNetActionDispatcher(method.Parameters[0].Type));
        }

        private static bool IsNetActionDispatcher(ITypeSymbol type)
        {
            return type.Name == "NetActionDispatcher" &&
                   type.ContainingNamespace.ToDisplayString() == "MetaMystia.Network";
        }

        private static void GenerateRegistry(SourceProductionContext context, ImmutableArray<BehaviorInfo> behaviors)
        {
            foreach (var behavior in behaviors.Where(static behavior => !behavior.HasRegister))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    MissingRegisterRule,
                    behavior.Location,
                    behavior.Name));
            }

            var calls = behaviors
                .Where(static behavior => behavior.HasRegister)
                .GroupBy(static behavior => behavior.QualifiedName)
                .Select(static group => group.First())
                .OrderBy(static behavior => behavior.QualifiedName)
                .ToArray();

            var source = GenerateSource(calls);
            context.AddSource(
                "NetActionBehaviorRegistry.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }

        private static string GenerateSource(BehaviorInfo[] behaviors)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("namespace MetaMystia.Network;");
            sb.AppendLine();
            sb.AppendLine("internal static partial class NetActionBehaviorRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial void RegisterAll(NetActionDispatcher dispatcher)");
            sb.AppendLine("    {");

            foreach (var behavior in behaviors)
                sb.AppendLine($"        {behavior.QualifiedName}.Register(dispatcher);");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private readonly struct BehaviorInfo
        {
            public readonly string Name;
            public readonly string QualifiedName;
            public readonly bool HasRegister;
            public readonly Location? Location;

            public BehaviorInfo(string name, string qualifiedName, bool hasRegister, Location? location)
            {
                Name = name;
                QualifiedName = qualifiedName;
                HasRegister = hasRegister;
                Location = location;
            }
        }
    }
}
