using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace MetaMystia.Generators
{
    /// <summary>
    /// 把 GameSchemaTypes 列出的游戏枚举镜像成不依赖游戏的 MetaMystia.Schema 类型。
    /// 只生成常量成员，产物不引用游戏程序集。
    /// </summary>
    [Generator]
    public sealed class GameSchemaGenerator : IIncrementalGenerator
    {
        private const string PropertyName = "build_property.GameSchemaTypes";
        private const string TargetNamespace = "MetaMystia.Schema";

        private static readonly DiagnosticDescriptor MissingType = new(
            "MMS001", "游戏枚举无法解析", "GameSchemaTypes 中的 '{0}' 解析失败，检查拼写与 interop 引用",
            "Schema", DiagnosticSeverity.Error, true);
        private static readonly DiagnosticDescriptor NotEnum = new(
            "MMS002", "不是枚举", "GameSchemaTypes 中的 '{0}' 不是枚举",
            "Schema", DiagnosticSeverity.Error, true);
        private static readonly DiagnosticDescriptor NameConflict = new(
            "MMS003", "镜像名称冲突", "'{0}' 与 '{1}' 生成同名类型，去掉其中一个或改用不同名字",
            "Schema", DiagnosticSeverity.Error, true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var types = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue(PropertyName, out var value);
                return value ?? "";
            });

            context.RegisterSourceOutput(
                context.CompilationProvider.Combine(types),
                static (output, input) => Emit(output, input.Left, input.Right));
        }

        private static void Emit(SourceProductionContext context, Compilation compilation, string types)
        {
            var emitted = new Dictionary<string, string>();
            foreach (var name in Split(types))
            {
                if (Resolve(compilation, name) is not { } symbol)
                {
                    context.ReportDiagnostic(Diagnostic.Create(MissingType, Location.None, name));
                    continue;
                }

                if (symbol.TypeKind != TypeKind.Enum)
                {
                    context.ReportDiagnostic(Diagnostic.Create(NotEnum, Location.None, name));
                    continue;
                }

                if (emitted.TryGetValue(symbol.Name, out var owner))
                {
                    context.ReportDiagnostic(Diagnostic.Create(NameConflict, Location.None, owner, name));
                    continue;
                }

                emitted.Add(symbol.Name, name);
                context.AddSource($"{symbol.Name}.schema.g.cs", SourceText.From(Generate(symbol, name), Encoding.UTF8));
            }
        }

        private static string Generate(INamedTypeSymbol symbol, string source)
        {
            var underlying = symbol.EnumUnderlyingType?.ToDisplayString() ?? "int";
            var text = new StringBuilder();
            text.AppendLine("// <auto-generated/>");
            text.AppendLine("// 由 GameSchemaGenerator 从游戏程序集生成，不要手改。");
            text.AppendLine();
            text.AppendLine($"namespace {TargetNamespace}");
            text.AppendLine("{");
            text.AppendLine($"    /// <summary>镜像自 <c>{source}</c>。</summary>");
            text.AppendLine($"    public enum {symbol.Name} : {underlying}");
            text.AppendLine("    {");

            foreach (var member in symbol.GetMembers())
                if (member is IFieldSymbol { HasConstantValue: true, ConstantValue: not null } field)
                    text.AppendLine($"        {Escape(field.Name)} = {Format(field.ConstantValue)},");

            text.AppendLine("    }");
            text.AppendLine("}");
            return text.ToString();
        }

        private static IEnumerable<string> Split(string types)
        {
            foreach (var part in types.Split(';'))
            {
                var name = part.Trim();
                if (name.Length > 0) yield return name;
            }
        }

        // 嵌套类型在元数据里用 '+' 分隔，这里从右往左逐个尝试。
        private static INamedTypeSymbol? Resolve(Compilation compilation, string name)
        {
            var candidate = name;
            while (true)
            {
                if (compilation.GetTypeByMetadataName(candidate) is { } found) return found;
                int split = candidate.LastIndexOf('.');
                if (split < 0) return null;
                candidate = candidate.Substring(0, split) + "+" + candidate.Substring(split + 1);
            }
        }

        private static string Format(object value) => value is IFormattable formattable
            ? formattable.ToString(null, CultureInfo.InvariantCulture)
            : value.ToString() ?? "0";

        private static string Escape(string name) =>
            SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : "@" + name;
    }
}
