using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MetaMystia.Generators
{
    /// <summary>
    /// 把自带的本地化 JSON 在编译期内联成常量。
    /// <para>
    /// 语言表原本从程序集嵌资里读，而读嵌资必须走 <c>System.Reflection</c>（模组侧禁用）。
    /// 内联之后运行时不再碰反射，也不必把 JSON 拆成额外文件，模组仍是"一份 dll + mod.json"的形态；
    /// JSON 文本原样进常量，解析仍由 <c>L10n.MergeJson</c> 在运行时用同一套代码做。
    /// </para>
    /// </summary>
    [Generator]
    public sealed class LocaleGenerator : IIncrementalGenerator
    {
        private const string TargetNamespace = "MetaMystia.UI";
        private const string TargetType = "LocaleResources";

        /// <summary>语言文件与生成成员名一一对应；成员名对应 <c>L10n</c> 的 <c>Language</c> 枚举。</summary>
        private static readonly (string FileName, string Member)[] Languages =
        {
            ("en.json", "English"),
            ("zh-CN.json", "ChineseSimplified"),
        };

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var sources = context.AdditionalTextsProvider
                .Select((text, _) => (Path.GetFileName(text.Path), Json: text.GetText()?.ToString() ?? string.Empty))
                .Where(file => Languages.Any(language =>
                    string.Equals(language.FileName, file.Item1, StringComparison.OrdinalIgnoreCase)))
                .Select((file, _) => new KeyValuePair<string, string>(file.Item1, file.Json))
                .Collect();

            context.RegisterSourceOutput(sources, (production, files) =>
                production.AddSource($"{TargetType}.g.cs", SourceText.From(Generate(files), Encoding.UTF8)));
        }

        private static string Generate(IReadOnlyCollection<KeyValuePair<string, string>> files)
        {
            var byName = files.ToDictionary(file => file.Key, file => file.Value, StringComparer.OrdinalIgnoreCase);
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine($"namespace {TargetNamespace};");
            source.AppendLine();
            source.AppendLine("/// <summary>编译期内联的自带本地化 JSON；由 MetaMystia.Generators 从 UI/Locales 生成。</summary>");
            source.AppendLine($"internal static class {TargetType}");
            source.AppendLine("{");
            foreach (var (fileName, member) in Languages)
            {
                // 缺一个文件就生成空串：JSON 解析会报错，比整份编译不过更容易看懂。
                byName.TryGetValue(fileName, out var json);
                source.AppendLine($"    /// <summary>{fileName} 的原始文本。</summary>");
                source.AppendLine($"    internal const string {member} = {RawLiteral(json ?? string.Empty)};");
                source.AppendLine();
            }

            source.Append("}");
            return source.ToString();
        }

        /// <summary>
        /// 把文本写成多行原始字符串字面量：括号长度取"文本里最长连续引号数 + 1"，至少 3。
        /// 结束括号顶格，于是文本每一行的缩进都满足 C# 对原始字面量的要求，内容也不需要转义。
        /// </summary>
        private static string RawLiteral(string content)
        {
            var fence = new string('"', Math.Max(3, LongestQuoteRun(content) + 1));
            return $"{fence}\n{content}\n{fence}";
        }

        private static int LongestQuoteRun(string content)
        {
            var longest = 0;
            var current = 0;
            foreach (var character in content)
            {
                current = character == '"' ? current + 1 : 0;
                if (current > longest)
                    longest = current;
            }

            return longest;
        }
    }
}
