<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../MetaMystia.Network/Network.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Update="Assembly-CSharp" Aliases="GameInterop" />
    <ProjectReference Include="../MetaMystia.Network/MetaMystia.Network.csproj" />
    <Compile Include="../MetaMystia.Mod/Managers/DayDestinationManager.cs" Link="DayDestinationManager.cs" />
    <Compile Include="../MetaMystia.Mod/Managers/BusinessStart.cs" Link="BusinessStart.cs" />
    <Compile Include="../MetaMystia.Mod/Managers/GameFlow.Transitions.cs" Link="GameFlow.Transitions.cs" />
    <Compile Include="../MetaMystia.Mod/Patches/Common/IzakayaSelectorPanelPatch.cs" Link="IzakayaSelectorPanelPatch.cs" />
    <Compile Include="../MetaMystia.Mod/Patches/HarmonyPrefixFlow.cs" Link="HarmonyPrefixFlow.cs" />
  </ItemGroup>
</Project>
