namespace MetaMystia.Network;

public enum GameMessageType : ushort
{
    Ping = 1,
    Pong = 2,
    Chat = 10,
    SelectIzakaya = 14,
    ConfirmIzakaya = 15,
    UpdatePrep = 16,
    PrepReady = 17,
    PrepAllReady = 18,
    NightCook = 19,
    ExtractFromCooker = 20,
    StoreFood = 21,
    StoreSellable = 22,
    ExtractFood = 23,
    QTE = 24,
    Buff = 25,
    GuestInvite = 26,
    GuestSpawn = 27,
    MoveToDesk = 28,
    MoveToQueue = 29,
    PlayerRepell = 30,
    GenerateOrder = 31,
    ServeSellable = 32,
    EvaluateOrder = 33,
    ConfirmServe = 34,
    GuestLeave = 35,
    SendFromQueue = 36,
    PatientDepletedQueue = 37,
    PatientDepletedDesk = 38,
    GuestKill = 39,
    FundEdit = 40,
    TipEdit = 41,
    ExpEdit = 42,
    PassionEdit = 43,
    IzakayaClose = 44,
    GuestRepell = 45,
    YuyukoFailed = 46,
    YuyukoLife = 47,
    DayDestinationIntent = 48,
    DayDestinationState = 49,
    DayDestinationConfirm = 50,
    YuyukoGuest = 51,
    YuyukoGuestBound = 52,
    RoomInitialState = 53,
    BusinessStart = 54,
}

public static class GameMessageRules
{
    public static MessageRule[] Create() =>
    [
        new((ushort)GameMessageType.Ping, [Route.Host]),
        new((ushort)GameMessageType.Pong, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.Chat, [Route.World], RoomScoped: false, MaxBytes: 4096),
        new((ushort)GameMessageType.SelectIzakaya, [Route.Room]),
        new((ushort)GameMessageType.ConfirmIzakaya, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.UpdatePrep, [Route.Host, Route.Room], HostBroadcastOnly: true),
        new((ushort)GameMessageType.PrepReady, [Route.Room]),
        new((ushort)GameMessageType.PrepAllReady, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.NightCook, [Route.Room]),
        new((ushort)GameMessageType.ExtractFromCooker, [Route.Room]),
        new((ushort)GameMessageType.StoreFood, [Route.Room]),
        new((ushort)GameMessageType.StoreSellable, [Route.Room]),
        new((ushort)GameMessageType.ExtractFood, [Route.Room]),
        new((ushort)GameMessageType.QTE, [Route.Room]),
        new((ushort)GameMessageType.Buff, [Route.Room]),
        new((ushort)GameMessageType.GuestInvite, [Route.Host]),
        new((ushort)GameMessageType.GuestSpawn, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.MoveToDesk, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.MoveToQueue, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.PlayerRepell, [Route.Host]),
        new((ushort)GameMessageType.GenerateOrder, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.ServeSellable, [Route.Host, Route.Room], HostBroadcastOnly: true),
        new((ushort)GameMessageType.EvaluateOrder, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.ConfirmServe, [Route.Host, Route.Room], HostBroadcastOnly: true),
        new((ushort)GameMessageType.GuestLeave, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.SendFromQueue, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.PatientDepletedQueue, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.PatientDepletedDesk, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.GuestKill, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.FundEdit, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.TipEdit, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.ExpEdit, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.PassionEdit, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.IzakayaClose, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.GuestRepell, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.YuyukoFailed, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.YuyukoLife, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.DayDestinationIntent, [Route.Host]),
        new((ushort)GameMessageType.DayDestinationState, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.DayDestinationConfirm, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.YuyukoGuest, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.YuyukoGuestBound, [Route.Host]),
        new((ushort)GameMessageType.RoomInitialState, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessageType.BusinessStart, [Route.Host, Route.Room], HostBroadcastOnly: true),
    ];
}
