namespace MetaMystia.Network;

public enum GameMessage : ushort
{
    Ping = 1,
    Pong = 2,
    Message = 10,
    SelectIzakaya = 14,
    ConfirmIzakaya = 15,
    UpdatePrep = 16,
    PrepReady = 17,
    PrepAllReady = 18,
    NightCook = 19,
    ExtractFromCooker = 20,
    StoreFood = 21,
    StoreSellable = 22,
    ExtractFood = 23,
    QTE = 24,
    Buff = 25,
    GuestInvite = 26,
    GuestSpawn = 27,
    MoveToDesk = 28,
    MoveToQueue = 29,
    PlayerRepell = 30,
    GenerateOrder = 31,
    ServeSellable = 32,
    EvaluateOrder = 33,
    ConfirmServe = 34,
    GuestLeave = 35,
    SendFromQueue = 36,
    PatientDepletedQueue = 37,
    PatientDepletedDesk = 38,
    GuestKill = 39,
    FundEdit = 40,
    TipEdit = 41,
    ExpEdit = 42,
    PassionEdit = 43,
    IzakayaClose = 44,
    GuestRepell = 45,
    YuyukoFailed = 46,
    YuyukoLife = 47,
    DayDestinationIntent = 48,
    DayDestinationState = 49,
    DayDestinationConfirm = 50,
    YuyukoGuest = 51,
    YuyukoGuestBound = 52,
    RoomReady = 53,
    BusinessStart = 54,
}

public static class GameMessageRules
{
    public static MessageRule[] Create() =>
    [
        new((ushort)GameMessage.Ping, [Route.Host]),
        new((ushort)GameMessage.Pong, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.Message, [Route.World], RoomScoped: false, MaxBytes: 4096),
        new((ushort)GameMessage.SelectIzakaya, [Route.Room]),
        new((ushort)GameMessage.ConfirmIzakaya, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.UpdatePrep, [Route.Room]),
        new((ushort)GameMessage.PrepReady, [Route.Room]),
        new((ushort)GameMessage.PrepAllReady, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.NightCook, [Route.Room]),
        new((ushort)GameMessage.ExtractFromCooker, [Route.Room]),
        new((ushort)GameMessage.StoreFood, [Route.Room]),
        new((ushort)GameMessage.StoreSellable, [Route.Room]),
        new((ushort)GameMessage.ExtractFood, [Route.Room]),
        new((ushort)GameMessage.QTE, [Route.Room]),
        new((ushort)GameMessage.Buff, [Route.Room]),
        new((ushort)GameMessage.GuestInvite, [Route.Host]),
        new((ushort)GameMessage.GuestSpawn, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.MoveToDesk, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.MoveToQueue, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.PlayerRepell, [Route.Host]),
        new((ushort)GameMessage.GenerateOrder, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.ServeSellable, [Route.Host, Route.Room], HostBroadcastOnly: true),
        new((ushort)GameMessage.EvaluateOrder, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.ConfirmServe, [Route.Host, Route.Room], HostBroadcastOnly: true),
        new((ushort)GameMessage.GuestLeave, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.SendFromQueue, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.PatientDepletedQueue, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.PatientDepletedDesk, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.GuestKill, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.FundEdit, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.TipEdit, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.ExpEdit, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.PassionEdit, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.IzakayaClose, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.GuestRepell, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.YuyukoFailed, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.YuyukoLife, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.DayDestinationIntent, [Route.Host]),
        new((ushort)GameMessage.DayDestinationState, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.DayDestinationConfirm, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.YuyukoGuest, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.YuyukoGuestBound, [Route.Host]),
        new((ushort)GameMessage.RoomReady, [Route.Room, Route.Player], HostOnly: true),
        new((ushort)GameMessage.BusinessStart, [Route.Host, Route.Room], HostBroadcastOnly: true),
    ];
}
