<Project>
  <Import Project="../../MetaMystia.local.props" Condition="Exists('../../MetaMystia.local.props')" />
  <Import Project="../../Versions.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
  <ItemGroup Condition="'$(MystiaInteropDir)' != ''">
    <Reference Include="Assembly-CSharp">
      <HintPath>$(MystiaInteropDir)Assembly-CSharp.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(MystiaInteropDir)Il2Cppmscorlib.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(MystiaInteropDir)UnityEngine.CoreModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Il2CppInterop.Runtime" Version="1.5.1" />
  </ItemGroup>
</Project>
